package cs3500.hw03;

import cs3500.hw02.Card;
import cs3500.hw03.PrintInteraction;
import cs3500.hw03.InputInteraction;
import org.junit.Test;

import java.io.IOException;
import java.io.StringReader;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.assertEquals;

/**
 * Tests for {@link WhistController} .
 */
public class WhistControllerTest {
  private void testRun(CardGameModel model, int numplayers, Interaction... interactions)
      throws IOException {
    StringBuilder UserInput = new StringBuilder();
    StringBuilder expectedOutput = new StringBuilder();

    for (Interaction interaction : interactions) {
      interaction.apply(UserInput, expectedOutput);
    }

    StringReader in = new StringReader(UserInput.toString());
    StringBuilder out = new StringBuilder();

    List<Card> deck = model.getDeck();
    Collections.sort(deck);
    Collections.reverse(deck);

    IWhistController testWhistController = new WhistController(in, out);
    testWhistController.startGame(model, numplayers, deck);

    assertEquals(expectedOutput.toString(), out.toString()+"\n");

  }

  @Test
  public void gameStateTwoPlayers() {
    CardGameModel whistGame = new WhistModel();

    Interaction[] interactions = new Interaction[] {
        new PrintInteraction("Number of Players: 2\n"
            + "Player 1: A♣, Q♣, 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: K♣, J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 0 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: Q♣, 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: K♣, J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 0 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: Q♣, 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 1 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 1 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 2 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 2 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 3 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 3 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 7 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 7 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 9 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 9 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 10 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 10 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 11 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 11 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 12 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 12 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 13 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n"
            + "Player 1: Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 13 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n"
            + "Player 1: Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 14 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 14 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n" + "Player 1: 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 15 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
            + "Player 1: 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 15 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
            + "Player 1: 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 16 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
            + "Player 1: 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 16 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
            + "Player 1: 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 17 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
            + "Player 1: 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 17 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
            + "Player 1: 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 18 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
            + "Player 1: 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 18 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
            + "Player 1: 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n" + "Player 2: A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 19 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 19 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
            + "Player 1: K♠, J♠, 9♠, 7♠, 5♠, 3♠\n" + "Player 2: Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 20 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: J♠, 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 20 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
            + "Player 1: J♠, 9♠, 7♠, 5♠, 3♠\n" + "Player 2: 10♠, 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 21 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: 9♠, 7♠, 5♠, 3♠\n"
            + "Player 2: 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 21 hands won\n"
            + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
            + "Player 1: 9♠, 7♠, 5♠, 3♠\n" + "Player 2: 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 22 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: 7♠, 5♠, 3♠\n" + "Player 2: 8♠, 6♠, 4♠, 2♠\n"
            + "Player 1: 22 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n" + "Player 1: 7♠, 5♠, 3♠\n" + "Player 2: 6♠, 4♠, 2♠\n"
            + "Player 1: 23 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: 5♠, 3♠\n" + "Player 2: 6♠, 4♠, 2♠\n"
            + "Player 1: 23 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n" + "Player 1: 5♠, 3♠\n" + "Player 2: 4♠, 2♠\n"
            + "Player 1: 24 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: 3♠\n" + "Player 2: 4♠, 2♠\n"
            + "Player 1: 24 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n" + "Player 1: 3♠\n" + "Player 2: 2♠\n"
            + "Player 1: 25 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
            + "Number of Players: 2\n" + "Player 1: \n" + "Player 2: 2♠\n"
            + "Player 1: 25 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
            + "Number of Players: 2\n" + "Player 1: \n" + "Player 2: \n"
            + "Player 1: 26 hands won\n" + "Player 2: 0 hands won\n" + "Game over. Player 1 won"),
        new InputInteraction("0\n" + "0\n" + "0\n" + "0\n"+ "0\n"+ "0\n"
            + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n"+ "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n" + "0\n" + "0\n"+ "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n")
    };

    try {
      testRun(whistGame, 2, interactions);
    } catch (IOException e) {
      e.printStackTrace();
    }

  }

  @Test
  public void playThrowsException() {
    CardGameModel whistGame = new WhistModel();

    Interaction[] interactions = new Interaction[] {
        new PrintInteraction(
            "Number of Players: 2\n"
                + "Player 1: A♣, Q♣, 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: K♣, J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 0 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Invalid input\n" + "Number of Players: 2\n"
                + "Player 1: A♣, Q♣, 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: K♣, J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 0 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: Q♣, 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: K♣, J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 0 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: Q♣, 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 1 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: J♣, 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 1 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 10♣, 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 2 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 9♣, 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 2 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 8♣, 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 3 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 7♣, 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 3 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 6♣, 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 5♣, 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 4♣, 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 3♣, A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 2♣, K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: A♦, Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: K♦, J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 7 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: Q♦, 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 7 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: J♦, 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 10♦, 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 9♦, 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 9 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 8♦, 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 9 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 7♦, 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 10 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 6♦, 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 10 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 5♦, 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 11 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 4♦, 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 11 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 3♦, A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 12 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 2♦, K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 12 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: A♥, Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 13 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: K♥, J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 13 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: Q♥, 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 14 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n"
                + "Player 1: 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: J♥, 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 14 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n"
                + "Player 1: 10♥, 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 15 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n" + "Player 1: 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 9♥, 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 15 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: 8♥, 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 16 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
                + "Player 1: 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 7♥, 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 16 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
                + "Player 1: 6♥, 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 17 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
                + "Player 1: 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 5♥, 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 17 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
                + "Player 1: 4♥, 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 18 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
                + "Player 1: 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 3♥, A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 18 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 2\n" + "Number of Players: 2\n"
                + "Player 1: 2♥, K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 19 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
                + "Player 1: K♠, J♠, 9♠, 7♠, 5♠, 3♠\n" + "Player 2: A♠, Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 19 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: K♠, J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 20 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
                + "Player 1: J♠, 9♠, 7♠, 5♠, 3♠\n" + "Player 2: Q♠, 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 20 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: J♠, 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 10♠, 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 21 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
                + "Player 1: 9♠, 7♠, 5♠, 3♠\n" + "Player 2: 10♠, 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 21 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: 9♠, 7♠, 5♠, 3♠\n"
                + "Player 2: 8♠, 6♠, 4♠, 2♠\n" + "Player 1: 22 hands won\n"
                + "Player 2: 0 hands won\n" + "Turn: Player 1\n" + "Number of Players: 2\n"
                + "Player 1: 7♠, 5♠, 3♠\n" + "Player 2: 8♠, 6♠, 4♠, 2♠\n"
                + "Player 1: 22 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: 7♠, 5♠, 3♠\n" + "Player 2: 6♠, 4♠, 2♠\n"
                + "Player 1: 23 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n" + "Player 1: 5♠, 3♠\n" + "Player 2: 6♠, 4♠, 2♠\n"
                + "Player 1: 23 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: 5♠, 3♠\n" + "Player 2: 4♠, 2♠\n"
                + "Player 1: 24 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n" + "Player 1: 3♠\n" + "Player 2: 4♠, 2♠\n"
                + "Player 1: 24 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: 3♠\n" + "Player 2: 2♠\n"
                + "Player 1: 25 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 1\n"
                + "Number of Players: 2\n" + "Player 1: \n" + "Player 2: 2♠\n"
                + "Player 1: 25 hands won\n" + "Player 2: 0 hands won\n" + "Turn: Player 2\n"
                + "Number of Players: 2\n" + "Player 1: \n" + "Player 2: \n"
                + "Player 1: 26 hands won\n" + "Player 2: 0 hands won\n"
                + "Game over. Player 1 won"
        ),
        new InputInteraction("100\n" + "0\n" + "0\n" + "0\n" + "0\n"+ "0\n"+ "0\n"
            + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n"+ "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n" + "0\n" + "0\n"+ "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n")
    };

    try {
      testRun(whistGame, 2, interactions);
    } catch (IOException e) {
      e.printStackTrace();
    }

  }


}

