package cs3500.hw04;

import cs3500.hw02.Card;
import cs3500.hw03.*;
import org.junit.Test;

import java.io.IOException;
import java.io.StringReader;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.assertEquals;

/**
 * Tests for {@link WhistController} .
 */
public class TrumpWhistControllerTest {

  @Test
  public void gameStateFivePlayers() {
    CardGameModel whistGame = new WhistModelBenCarson();

    Interaction[] interactions = new Interaction[] {
        new PrintInteraction("Number of Players: 5\n"
            + "Player 1: A♣, 9♣, 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: K♣, 8♣, 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: Q♣, 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: J♣, 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 10♣, 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 0 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 1\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 9♣, 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: K♣, 8♣, 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: Q♣, 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: J♣, 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 10♣, 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 0 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 2\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 9♣, 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 8♣, 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: Q♣, 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: J♣, 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 10♣, 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 0 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 3\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 9♣, 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 8♣, 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: J♣, 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 10♣, 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 0 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 4\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 9♣, 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 8♣, 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 10♣, 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 0 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 5\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 9♣, 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 8♣, 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 1 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 1\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 8♣, 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 1 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 2\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 7♣, 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 1 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 3\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 6♣, A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 1 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 4\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 5♣, K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 1 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 5\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 4♣, Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 2 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 1\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 3♣, J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 2 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 2\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 2♣, 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 2 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 3\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: A♦, 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 2 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 4\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n" + "Player 4: 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: K♦, 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 2 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 5\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: Q♦, 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n" + "Player 4: 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 3 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 1\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: J♦, 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n" + "Player 4: 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 3 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 2\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 10♦, 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 3 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 3\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n"
            + "Player 1: 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n" + "Player 2: 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 5♦, K♥, 8♥, 3♥, J♠, 6♠\n" + "Player 4: 9♦, 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 3 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 4\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 8♦, 3♦, J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 3 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 5\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n"
            + "Player 1: 7♦, 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n" + "Player 2: 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 5♦, K♥, 8♥, 3♥, J♠, 6♠\n" + "Player 4: 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n"
            + "Player 5: 3♦, J♥, 6♥, A♠, 9♠, 4♠\n" + "Player 1: 4 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 1\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 6♦, A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 3♦, J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 2\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 5♦, K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 3♦, J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 3\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 4♦, Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 3♦, J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 4\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 3♦, J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 4 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 5\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 2♦, 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 1\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: A♥, 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 2\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: K♥, 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 3\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: Q♥, 7♥, 2♥, 10♠, 5♠\n" + "Player 5: J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 4\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 7♥, 2♥, 10♠, 5♠\n" + "Player 5: J♥, 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 5 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 5\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 10♥, 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 1\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 9♥, 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 2\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 8♥, 3♥, J♠, 6♠\n"
            + "Player 4: 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 3\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 3♥, J♠, 6♠\n"
            + "Player 4: 7♥, 2♥, 10♠, 5♠\n" + "Player 5: 6♥, A♠, 9♠, 4♠\n"
            + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 4\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 5♥, K♠, 8♠, 3♠\n"
            + "Player 2: 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 3♥, J♠, 6♠\n" + "Player 4: 2♥, 10♠, 5♠\n"
            + "Player 5: 6♥, A♠, 9♠, 4♠\n" + "Player 1: 6 hands won\n" + "Player 2: 0 hands won\n"
            + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n"
            + "Turn: Player 5\n" + "Trump Suit: ♣\n" + "Number of Players: 5\n"
            + "Player 1: 5♥, K♠, 8♠, 3♠\n" + "Player 2: 4♥, Q♠, 7♠, 2♠\n" + "Player 3: 3♥, J♠, 6♠\n"
            + "Player 4: 2♥, 10♠, 5♠\n" + "Player 5: A♠, 9♠, 4♠\n" + "Player 1: 7 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 1\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: K♠, 8♠, 3♠\n" + "Player 2: 4♥, Q♠, 7♠, 2♠\n"
            + "Player 3: 3♥, J♠, 6♠\n" + "Player 4: 2♥, 10♠, 5♠\n" + "Player 5: A♠, 9♠, 4♠\n"
            + "Player 1: 7 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 2\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: K♠, 8♠, 3♠\n"
            + "Player 2: Q♠, 7♠, 2♠\n" + "Player 3: 3♥, J♠, 6♠\n" + "Player 4: 2♥, 10♠, 5♠\n"
            + "Player 5: A♠, 9♠, 4♠\n" + "Player 1: 7 hands won\n" + "Player 2: 0 hands won\n"
            + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n"
            + "Turn: Player 3\n" + "Trump Suit: ♣\n" + "Number of Players: 5\n"
            + "Player 1: K♠, 8♠, 3♠\n" + "Player 2: Q♠, 7♠, 2♠\n" + "Player 3: J♠, 6♠\n"
            + "Player 4: 2♥, 10♠, 5♠\n" + "Player 5: A♠, 9♠, 4♠\n" + "Player 1: 7 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 4\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: K♠, 8♠, 3♠\n" + "Player 2: Q♠, 7♠, 2♠\n"
            + "Player 3: J♠, 6♠\n" + "Player 4: 10♠, 5♠\n" + "Player 5: A♠, 9♠, 4♠\n"
            + "Player 1: 7 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 5\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: K♠, 8♠, 3♠\n"
            + "Player 2: Q♠, 7♠, 2♠\n" + "Player 3: J♠, 6♠\n" + "Player 4: 10♠, 5♠\n"
            + "Player 5: 9♠, 4♠\n" + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n"
            + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n"
            + "Turn: Player 1\n" + "Trump Suit: ♣\n" + "Number of Players: 5\n"
            + "Player 1: 8♠, 3♠\n" + "Player 2: Q♠, 7♠, 2♠\n" + "Player 3: J♠, 6♠\n"
            + "Player 4: 10♠, 5♠\n" + "Player 5: 9♠, 4♠\n" + "Player 1: 8 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 2\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 8♠, 3♠\n" + "Player 2: 7♠, 2♠\n"
            + "Player 3: J♠, 6♠\n" + "Player 4: 10♠, 5♠\n" + "Player 5: 9♠, 4♠\n"
            + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 3\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 8♠, 3♠\n"
            + "Player 2: 7♠, 2♠\n" + "Player 3: 6♠\n" + "Player 4: 10♠, 5♠\n" + "Player 5: 9♠, 4♠\n"
            + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 4\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 8♠, 3♠\n"
            + "Player 2: 7♠, 2♠\n" + "Player 3: 6♠\n" + "Player 4: 5♠\n" + "Player 5: 9♠, 4♠\n"
            + "Player 1: 8 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 5\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 8♠, 3♠\n"
            + "Player 2: 7♠, 2♠\n" + "Player 3: 6♠\n" + "Player 4: 5♠\n" + "Player 5: 4♠\n"
            + "Player 1: 9 hands won\n" + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n"
            + "Player 4: 0 hands won\n" + "Player 5: 0 hands won\n" + "Turn: Player 1\n"
            + "Trump Suit: ♣\n" + "Number of Players: 5\n" + "Player 1: 3♠\n" + "Player 2: 7♠, 2♠\n"
            + "Player 3: 6♠\n" + "Player 4: 5♠\n" + "Player 5: 4♠\n" + "Player 1: 9 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 2\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 3♠\n" + "Player 2: 2♠\n" + "Player 3: 6♠\n"
            + "Player 4: 5♠\n" + "Player 5: 4♠\n" + "Player 1: 9 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 3\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 3♠\n" + "Player 2: 2♠\n" + "Player 3: \n"
            + "Player 4: 5♠\n" + "Player 5: 4♠\n" + "Player 1: 9 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 4\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 3♠\n" + "Player 2: 2♠\n" + "Player 3: \n"
            + "Player 4: \n" + "Player 5: 4♠\n" + "Player 1: 9 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 5\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: 3♠\n" + "Player 2: 2♠\n" + "Player 3: \n"
            + "Player 4: \n" + "Player 5: \n" + "Player 1: 10 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 1\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: \n" + "Player 2: 2♠\n" + "Player 3: \n"
            + "Player 4: \n" + "Player 5: \n" + "Player 1: 10 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Turn: Player 2\n" + "Trump Suit: ♣\n"
            + "Number of Players: 5\n" + "Player 1: \n" + "Player 2: \n" + "Player 3: \n"
            + "Player 4: \n" + "Player 5: \n" + "Player 1: 11 hands won\n"
            + "Player 2: 0 hands won\n" + "Player 3: 0 hands won\n" + "Player 4: 0 hands won\n"
            + "Player 5: 0 hands won\n" + "Game over. Player 1 won"),
        new InputInteraction("0\n" + "0\n" + "0\n" + "0\n"+ "0\n"+ "0\n"
            + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n"+ "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n" + "0\n" + "0\n"+ "0\n"+ "0\n" + "0\n" + "0\n" + "0\n" + "0\n" + "0\n"
            + "0\n" + "0\n")

    };

    try {
      testRun(whistGame, 5, interactions);
    } catch (IOException e) {
      e.printStackTrace();
    }

  }

  private void testRun(CardGameModel model, int numplayers, Interaction... interactions)
      throws IOException {
    StringBuilder UserInput = new StringBuilder();
    StringBuilder expectedOutput = new StringBuilder();

    for (Interaction interaction : interactions) {
      interaction.apply(UserInput, expectedOutput);
    }

    StringReader in = new StringReader(UserInput.toString());
    StringBuilder out = new StringBuilder();

    List<Card> deck = model.getDeck();
    Collections.sort(deck);
    Collections.reverse(deck);

    IWhistController testWhistController = new WhistController(in, out);
    testWhistController.startGame(model, numplayers, deck);

    assertEquals(expectedOutput.toString(), out.toString()+"\n");

  }

}
